### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Remi-Gau**
no big changes 

mostly cleaning code and breaking things into smaller sub-functions.

most noticeable change:
- added some defaults so we have less things to specify in our `cfg` and `expParameters` if running a fairly normal thing.
- renamed some fields to make them match those from CPP_PTB.
- no need to run `checkCFG` as `createFilename` does it for you.
- but this means that you now need to call ask for both `cfg` AND `expParameters` to be returned by `createFilename` like this:
```
[cfg, expParameters] = createFilename(cfg, expParameters);
```
-  have also improved the examples in the `tests` folder to make them easier to understand how to use all of this

### CODE REVIEW

**Comment by CerenB** [comment]
heya! sorry that i'm falling behind a bit with these light speed PRs :) 
now, I think you call somewhere `cfg.testingDevice` instead of `cfg.device` right? 
and also you changed from `scanner` to `mri`

**Comment by CerenB** [comment]
testing is not working for me. `runTest.m` function calls:
```
 if ~nargin
        pth = fileparts(mfilename('fullpath'));
    end
```
when I manually provide the pth as the current directory, it still fails. What am I doing wrong?

**Comment by Remi-Gau** [comment]
> heya! sorry that i'm falling behind a bit with these light speed PRs :)
> now, I think you call somewhere `cfg.testingDevice` instead of `cfg.device` right?
> and also you changed from `scanner` to `mri`

yes that's correct.

`device` was not clear enough (when mixed with CPP_PTB it could be audio device keyboard... I thought this was clearer.

Same for `scanner` as  `mri` is less ambiguous.

**Comment by Remi-Gau** [comment]
> testing is not working for me. `runTest.m` function calls:
> 
> ```
>  if ~nargin
>         pth = fileparts(mfilename('fullpath'));
>     end
> ```
> 
> when I manually provide the pth as the current directory, it still fails. What am I doing wrong?

@CerenB what is the error message?

**Comment by CerenB** [comment]
@Remi-Gau I think the error was Ceren didn't have enough coffee. Because now it works! Sorry to bother you with this error. I took care of it.

**Pull request merged**
