### PR TITLE
try miss_hit linter with travis

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Comment by marcobarilari** [comment]
when `miss_hit` will become automatic, then Travis will run the code editor on all the code pushed within the pr, is this correct? Or, since it checks in `pwd` to all the code in the repo?

Also, will the edited code show up as a commit?

Sorry for all the question :) you can ignore them until we will have the occasion to nerd out about this in person

**Comment by Remi-Gau** [comment]
OK I managed to make it work.

So right now travis has 2 independent "jobs":
- run the unit tests: make sure they pass
- uses miss_hit to check all the `.m` files in the CPP_BIDS folder and subfolders (not just the "new" stuff of the PR) to see that our code conforms to our guidelines.

You can check the travis details to know which one failed: https://github.com/cpp-lln-lab/CPP_BIDS/pull/46/checks?check_run_id=896173512

And then look at the report for each job: for example: https://travis-ci.com/github/cpp-lln-lab/CPP_BIDS/jobs/363522080

Travsi won't fix our code for us. Maybe we could have something that works like Sourcery that sends a PR to fix our code, but I don't the skill or time to build such bot. :smile: 
But if you have some time to kill.

**Comment by Remi-Gau** [comment]
OK the linter via travis works.

So even though technically this is a "fail" I will merge so that we can start making this part of our workflow

**Comment by marcobarilari** [comment]
My inner Marie Kondo approves

**Pull request merged**
