### PR TITLE
add option to save a tsv  filtered event file 

### PR DESCRIPTION
**Pull request by marcobarilari**
2 things:

1. the tsv has only 1 line and I don't know why, any idea?
2. LMK what you think about the name of the output file, have no clue if it could make sense this way

### CODE REVIEW

**Review by CerenB — COMMENTED** [review]
Well I'm a bit lost in yours so I'll simply tell how I'm using your function. I'm guessing your varargin{1} is already the file name. So you do not need to create a tag for it. Maybe I'm wrong.

`tsvFile = 'sub-002_ses-001_task-RhythmCategBlock_run-001_events.tsv';
`
`outputFiltered = readAndFilterLogfile('trial_type', 'block', tsvFile);`

```
% convert back to struc to save in .tsv 
outputFiltered = dataset2struct(outputFiltered);

%write into tsv file
bids.util.tsvwrite(tsvFile,outputFiltered);
```

**Comment by marcobarilari** [comment]
that way you overwrite your file, no?

**Comment by marcobarilari** [comment]
a solution would be to save the filtered file with the same name in a folder at the file path using the 'tag' as folder name

**Comment by Remi-Gau** [comment]
I think that by default we should NOT overwrite the file but output a file with the suffix `_filtered`.

Though we could let the user specify what name they want to give it.

Will create a test for that function.

**Comment by Remi-Gau** [comment]
related issues:
- https://github.com/cpp-lln-lab/CPP_PTB/issues/77
- https://github.com/cpp-lln-lab/CPP_PTB/issues/78

**Comment by CerenB** [comment]
> I think that by default we should NOT overwrite the file but output a file with the suffix `_filtered`.
> 
> Though we could let the user specify what name they want to give it.
> 
> Will create a test for that function.

I wonder BIDS validator would complain if we have `_filtered.tsv` file but not corresponding` .nii `file?

**Comment by Remi-Gau** [comment]
> > I think that by default we should NOT overwrite the file but output a file with the suffix `_filtered`.
> > Though we could let the user specify what name they want to give it.
> > Will create a test for that function.
> 
> I wonder BIDS validator would complain if we have `_filtered.tsv` file but not corresponding`.nii`file?

yes it will !

but all of this should probably happen in your source data, not your raw data set.

**Comment by CerenB** [comment]
> but all of this should probably happen in your source data, not your raw data set.

if I'm going to use this filtered for contrasting, why it should be in the `sourcedata`? Not that I'm objecting to it. But is it OK to use things in the `sourcedata` as logfile ==setting contrasts ? So the` _tsv` file in the `func` folder is for decoration? :D

**Comment by CerenB** [comment]
(sorry so many confusions around `rawdata`, `sourcedata` :D and `func`)

**Comment by Remi-Gau** [comment]
in very brief
- source: the stuff that comes out the scanner or your PTB script ; the place where you can rename ; filter ; cut and paste
- raw : the actual BIDS data set. Once you have it ready DON'T TOUCH IT
- derivatives: anything that comes from raw

Because having something with `_filtered.tsv` will not be BIDS compatible, it must: either

**Review by Remi-Gau — APPROVED** [review]
I made some changes myself when creating the test. :-)

**Comment by CerenB** [comment]
this is still open issue right? I see the `.tsv` file is only producing 1-line instead of saving the full output structure. I see it's because of how `readAndFilterLogfile` is creating the data structure and how `tsvwrite` function reads, basically the dimensions do not match. the output `readandFilterLogfile` is `size = 1`, and `tsvwrite` goes through that `size` option. 
The `test_readAndFilter `does not fail because it does not look at how `.tsv` file is saved - which is only saving the 1-line of the output.

**Comment by CerenB** [comment]
I made it work with the following - as I mentioned above couple of days ago:
```
% convert back to struc to save in .tsv 
outputFiltered = dataset2struct(outputFiltered);

%write into tsv file
bids.util.tsvwrite(tsvFile,outputFiltered);
```

**Comment by Remi-Gau** [comment]
> @Remi-Gau and @marcobarilari this is still open issue right? I see the `.tsv` file is only producing 1-line instead of saving the full output structure. I see it's because of how `readAndFilterLogfile` is creating the data structure and how `tsvwrite` function reads, basically the dimensions do not match. the output `readandFilterLogfile` is `size = 1`, and `tsvwrite` goes through that `size` option.
> The `test_readAndFilter `does not fail because it does not look at how `.tsv` file is saved - which is only saving the 1-line of the output.

I checked your branch.

I think that maybe it is more due to this:
https://github.com/cpp-lln-lab/CPP_BIDS/blob/26cd875cf6f52cf4d76f0c11cd91a3ff2c2d86fe/src/readAndFilterLogfile.m#L77

```
    % Convert the structure to dataset
    try
        outputFiltered = struct2dataset(output);
    catch
        % dataset not yet supported by octave
        outputFiltered = output;
    end

    if saveOutputTsv

        bids.util.tsvwrite(outputFileName, output);  <------------- We have created `outputFiltered`, but we don't save `output` 

    end
```

**Comment by Remi-Gau** [comment]
Need to find a way to make the test fail to show that this is a bug and then we can fix it.

**Comment by marcobarilari** [comment]
> I made it work with the following - as I mentioned above couple of days ago:
> 
> % convert back to struc to save in .tsv 
> outputFiltered = dataset2struct(outputFiltered);
> 
> %write into tsv file
> bids.util.tsvwrite(tsvFile,outputFiltered);

I am super confused by what is a structure for matlab, apparently there are 2 versions: taking our script as an example

(1) `output` is a 1x1 struc

```matlab
output = 

  struct with fields:

               onset: [96×1 double]
            duration: [96×1 double]
          trial_type: {96×1 cell}
           direction: [96×1 double]
               speed: [96×1 double]
              target: [96×1 double]
               event: [96×1 double]
               block: [96×1 double]
             keyName: {96×1 cell}
    fixationPosition: [96×1 double]
    aperturePosition: [96×1 double]
```

(2) `outputFiltered = dataset2struct(outputFiltered);` is a 96x1 struct

```matlab
outputFiltered = 

  96×1 struct array with fields:

    onset
    duration
    trial_type
    direction
    speed
    target
    event
    block
    keyName
    fixationPosition
    aperturePosition
```

bot have 1 as output of `isstruct` but only one of the two, the latter, is the one that is liked by tsvwrite

¯\_(ツ)_/¯

**Comment by Remi-Gau** [comment]
Wow !!! 

I think you are onto something Marco ! Thanks. This would have taken me ages to find.

**Comment by Remi-Gau** [comment]
yup that's it.

if you do 
content = tsvread(file)

and then
tsvwrite(content)

You only get the first line...

So the "format" of the structure is changed as Marco mentioned.

Maybe worth pointing out in the bids-matlab repo: am trying to organize a meeting amongst the developpers there.

**Pull request merged**
